# -*- coding: utf-8 -*-
"""Zomato-EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5oSR0V_otzWrc2DldJxvUndTe6q4FHG
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
# %matplotlib inline

df = pd.read_csv(
    "zomato.csv",
    engine="python",
    on_bad_lines="skip"
)
df

df.columns

df.info()

df.isnull().sum()

df.drop(['url','address','phone','menu_item','dish_liked','reviews_list','listed_in(city)'],axis=1,inplace=True)
df.head(5)

df.info()

df.isnull()

df.isnull().sum()

df.rename(columns={'name':'restaurants','book_table':'booking','rate':'rating','approx_cost(for two people)':'cost','listed_in(type)':'types'},inplace=True)
df.head(5)

len(df)

df.dropna(inplace=True)

df.isnull().values.any()

df.info()

df[df.duplicated()].count().sum()

df.drop_duplicates(inplace=True)

df[df.duplicated()].count().sum()

df['rating'].unique()

df['rating'].replace("NEW|-",'0',regex=True).replace('/5','',regex=True).unique()

df['rating'].isnull().sum()

df['location'].unique()

df['location'].isnull().sum()

df['cost'].unique()

df['cost'].isnull().sum()

df['cost'] = df['cost'].replace(",",'',regex=True).astype(int)

df.cost.unique()

df['booking'].unique()

df['booking'].isnull().sum()

df['online_order'].unique()

df['online_order'].isnull().sum()

df['rest_type'].unique()

b = df['rest_type'].value_counts()
b

df['types'].unique()

df['types'].value_counts()

df['cuisines'].isnull().sum()

df['cuisines'].value_counts()

df['restaurants'].unique()

df.groupby('restaurants').count().head()

df['restaurants']=df['restaurants'].str.replace('[Ãx][^A-Za-z]+','',regex=True)

df.groupby('restaurants').count().head()

df.info()

df.isnull().sum()

df.to_csv('./clean_zomato.csv')

type1=df['rest_type'].value_counts().head(5)
type1.to_frame()

"""•	Restaurant Type"""

fig = px.bar(x= type1.index,
             y= type1,
            color= type1.index,
            title='Restaurant type',labels={'x':'Restaurant','y':'Count of Restaurant'}
            )
fig.show()

fig=px.bar(x=type1.index,
           y=type1,
           color=type1.index # Each bar is colored differently
           ,title='Restaurant type',labels={'x':'Restaurant','y':'Count of Restaurant'} # changes x and y label
          )
fig.show()

"""•	Restaurants delivering Online or not"""

online_or_not = df['online_order'].value_counts()
online_or_not

fig2 = px.pie(online_or_not,
             title = ' Delivering Online or Not',
              values = online_or_not,
              names = online_or_not.index
             )
fig2.show()

"""•Restaurants allowing table booking or not     """

df['booking'].value_counts()

fig = px.bar(df,x='booking', color = 'booking'
    ,title="table booking or not"
)
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)





fig.show()

"""•	Table booking Rate vs Rate  """

fig= px.box(df,x='booking',
               y='rating',
            color='booking'
               )
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

"""Online Order vs Rate"""

fig = px.violin(df,x='online_order', y="rating",
                color='online_order',

                 # draw box plot inside the violin
                points='outliers', # can be 'outliers', or False
               )
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

"""•	Best Location"""

loc_vote = df.groupby('location')['votes'].sum()
loc_vote = loc_vote.nlargest(5).sort_values()
loc_vote

fig = px.bar(x=loc_vote.index,
            y= loc_vote,
            color=loc_vote.index,
             title ='Best Location',labels={'x':'location','y':'votes'}
            )
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

"""•	Cost of Restaurant"""

fig = px.histogram(df['cost'],nbins=100)
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

df['rating'] = (
    df['rating']
    .astype(str)
    .str.split('/')
    .str[0]
)

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

vote = (
    df.groupby('restaurants', as_index=False)
      .agg({
          'votes': 'mean',
          'rating': 'mean'
      })
      .sort_values(by=['rating', 'votes'], ascending=False)
      .head(10)
)

"""Best Location by Votes

(Relation between Location and Votes)
"""

fig = px.bar(
    x=loc_vote.index,
    y=loc_vote.values,
    color=loc_vote.index,
    title='Best location by votes',
    labels={'x': 'Location', 'y': 'Votes'}
)
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

"""Best Location by Rating

(Relation between Location and Rating)
"""

fig=px.bar(y=vote['rating'],
           x=vote.index,
           color=vote.index # Each bar is colored differently
           ,title='Best location by rating',labels={'x':'Location','y':'Rating'} # changes x and y label
          )
fig.update_layout(
    width=700,   # 👈 change this
    height=400   # 👈 and this
)

fig.show()

"""Relation between cost and rating"""

fig=px.scatter(df,x='cost',y='rating',color='online_order')
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

"""Relation between Location and Type"""

fig = px.bar(df,x="types",y ="rating",color='types')
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

"""•	No. of restaurants in a Location"""

df.head(5)

fig = px.bar(df,x="location",color='location')
fig.show()

"""•	Gaussian Rest type and Rating

•	Most famous restaurant chains in Bengaluru
"""

fam = df['restaurants'].value_counts()
fam

top_chains_df = fam.reset_index()
top_chains_df.columns = ['Restaurant_Name', 'Outlet_Count']
top_chains_df.columns

top_chains_df = top_chains_df.sort_values(
    by='Outlet_Count',
    ascending=False
)

import plotly.express as px

fig = px.bar(
    top_chains_df,
    x='Restaurant_Name',
    y='Outlet_Count',
    color='Restaurant_Name',
    orientation='h',
    title='Most Famous Restaurant Chains in Bengaluru'
)
fig.show()







